@host = http://localhost:5001

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZXYtdXNlciIsInJvbGUiOlsid3JpdGUiLCJyZWFkIl0sImlzcyI6InJlY3J1aXRtZW50LXBsYXRmb3JtIiwiYXVkIjoicmVjcnVpdG1lbnQtcGxhdGZvcm0iLCJuYmYiOjE3Nzk0NjUzNzUsImV4cCI6MTc3OTUwMTM3NX0.Ihf2ApOAwHrewePU4ssu4fUvg_3GcipfO0bZt1MVrb4

POST {{host}}/health
Accept: application/json

###

POST {{host}}/inventory
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productId": "019e51c1-d535-7455-8278-f4cb0e069ee2",
  "quantity": 1
}

###
